[platformio]
test_dir = tests
default_envs = esp32_run

[env:esp32_run]
platform = espressif32
board = esp32doit-devkit-v1
framework = espidf
upload_speed = 921600
monitor_speed = 115200

[env:esp32_test]
platform = espressif32
board = esp32doit-devkit-v1
framework = espidf
monitor_speed = 115200
test_framework = unity
test_build_src = yes
build_flags = -D PIO_UNIT_TESTING